services:
  db:
    image: postgres:17.2
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
#    ports:
#      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
